#!/usr/bin/python

from os import listdir, makedirs, chown
from os.path import isdir, join
from pwd import getpwnam
from grp import getgrnam
from shutil import copyfile
from errno import EEXIST
from subprocess import check_output, call

plistname = "com.fotokem.downloadManager.plist"

userspath = "/Users"
agentpath = "Library/LaunchAgents"
utemplate = "/System/Library/User Template/Non_localized"

def getuserid(name):
  try:
    return getpwnam(name)[2]
  except:
    return -1

groupid = getgrnam("staff")[2]
for username in listdir(userspath):
  userid = getuserid(username)
  if isdir(join(userspath,username)) and userid > 0:
    try:
      makedirs(join(userspath,username,agentpath), 0700)
    except OSError as exc:
      if exc.errno != EEXIST:
        raise exc
      pass
    copyfile(join(utemplate,agentpath,plistname),join(userspath,username,agentpath,plistname))
    chown(join(userspath,username,agentpath,plistname),userid,groupid)
    chown(join(userspath,username,agentpath),userid,groupid)

consoleuser = check_output( "ls -l /dev/console | cut -d ' ' -f4", shell=True).strip()
if consoleuser != "root":
    cmd = "su - %s -c 'launchctl load -w %s/%s/%s/%s'" % (consoleuser, userspath, consoleuser, agentpath, plistname)
    call(cmd, shell=True)
